In [1]:
import numpy as np

1. Crear un arreglo con todos los numeros pares del 10 al 50

In [9]:
numero = np.arange(10, 51, 2)
print(numero)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


2. Crear una matriz 3x3 con valores del 0 al 8

In [66]:
a = np.array([(0, 1, 2), (3, 4, 5), (6, 7, 8)])
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
b = np.arange(9).reshape(3, 3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Utilizar numpy para generar un arreglo de 25 numeros aleatorioas

In [67]:
c = np.random.randint(50, size=25)
print(c)

[41  0 13  6  4 29  3  5 23  2 13 44 41  8 20 30 17 11  5 38 37 42 33 49
  3]


4. Crea un arreglo de una dimension e imprime el valor de la suma de todos sus elementos

In [58]:
d = np.random.randint(10, size = 20)
print(d)
print(d.sum())

[3 0 2 7 8 2 6 7 2 6 0 3 6 0 9 1 4 8 5 8]
87


5. Crea un arreglo de una dimension e imprime el valor de la media de todos sus elementos

In [69]:
e = np.random.randint(20, size = 15)
print(e)
print(round(e.mean(), 2))

[ 6  2 11 14 13  2 15 13 10 12 18 10  2  8  5]
9.4
